### ISSUE TITLE
Module-3 assignment- Have issues in identifying elements

### ISSUE THREAD

**Issue by Sankaramurthy** [tabhresh/Edureka_6thApril#1]
1. Could get the Xpath only for the "Selenium Course" could not find the Xpath for the subject.
2.  Could not get "All courses" Xpath. Copy pasted the Xpath from copy Xpath option. 

below is the code 

package com.selenium.training;

import java.util.NoSuchElementException;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;

public class XpathWait {

	public static void main(String[] args) {
		// Module 3: XPath Functions And Waits In Selenium

	System.setProperty("webdriver.chrome.driver", "D:\\Seleium Project\\Istallation Stuff\\Exe Files\\chromedriver\\chromedriver.exe");
	
	//Chrome driver is launched with Webdriver 
	WebDriver driver = new ChromeDriver();	
	// page timout of 10 seconds added
	driver.manage().timeouts().pageLoadTimeout(10,TimeUnit.SECONDS)	;
	
	// Edureka home page launched
	
	driver.navigate().to("https://www.edureka.co/");
	// browser maximized
	driver.manage().window().maximize();
	//implicit wait of  11 seconds added for all browsers
	driver.manage().timeouts().implicitlyWait(11, TimeUnit.SECONDS);
	
	// complete script timeout period is set to 100 seconds
	driver.manage().timeouts().setScriptTimeout(100, TimeUnit.SECONDS);
	
	// searching for Selenium  training and opening it
	driver.findElement(By.xpath("// input [@ id=\"search-inp\"]")).sendKeys("Selenium");
	driver.findElement(By.xpath("//i[@id=\"search-button-top\"]")).click();
	driver.findElement(By.xpath("//img [@src=\"https://d1jnx9ba8s6j9r.cloudfront.net/imgver.1538723273/img/s/co_img_535_1529999716.png\"]")).click();
	// valiating if the page opend is selenium training page 
	String course_title = driver.getTitle();
	
	if (course_title.contentEquals("Selenium Certification | Selenium Training | Selenium Course - Edureka")){
		
			System.out.println("Page loaded is :" +driver.getTitle());	
	}
	else {System.out.println("Selenium Traiing Page not loaded"); }
	
	
	// navigating back to the previous page 
	driver.navigate().back();
	driver.manage().timeouts().implicitlyWait(11, TimeUnit.SECONDS);
	
		/*
		 * WebDriver driver1 = new ChromeDriver();
		 * 
		 * // i could not get the right element locator for "all courses" lik. I had to
		 * copy paste the system provided XPath . Need help on this
		 * driver1.findElement(By.xpath("//*[@id=\"navbar\"]/ul/li[2]/a")).click();
		 * 
		 * Wait wait = new FluentWait(driver1).withTimeout(30,
		 * SECONDS).pollingEvery(5,SECODS).ignoring(NoSuchElementException.class);
		 */
	
	driver.findElement(By.xpath("//*[@id=\"navbar\"]/ul/li[2]/a")).click();
	
	driver.quit();
	}

}

**Comment by tabhresh** [comment]
I tried to check your code but since Edureka site is changing at a very frequently I would request you to use any other site and practice on that and will update the team
