### ISSUE TITLE
Module 4 -Assignment- Element identification issue

### ISSUE THREAD

**Issue by Sankaramurthy** [tabhresh/Edureka_6thApril#2]
could not code for the full assignment, got struck at selecting the travel date, orgin and destinations as i could not create xpath to identify the elements

package com.selenium.training;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class IndigoBooking {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
        System.setProperty("webdriver.chrome.driver", "D:\\Seleium Project\\Istallation Stuff\\Exe Files\\chromedriver\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().deleteAllCookies();
		
		driver.get("https://www.goindigo.in/?linkNav=home_header");
		

		// select one way trip
		
		driver.findElement(By.xpath("//label [@ for=\"oneWayTrip\"]")).click();	
		driver.findElement(By.name("or-src")).sendKeys("Bengaluru (BLR)");
	//	driver.findElement(By.name("or-dest")).sendKeys("Lucknow (LKO)");
		//driver.findElement(By.xpath("// input [@name=\"or-dest\"] //following :: input[19]")).sendKeys("3");
		//driver.findElement(By.xpath("// input [@name=\"or-dest\"] //following :: input[20]")).sendKeys("2");
	}

}

**Comment by tabhresh** [comment]
did you check the solution for the assignment?
