### ISSUE TITLE
Myntra.com webpage shows a alert message. could not handle that through alert. 

### ISSUE THREAD

**Issue by Sankaramurthy** [tabhresh/Edureka_6thApril#3]
> Below is the code i used:
> --------------------------------
> 

package module5;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class MouseEvent {

	public static void main(String[] args) {
 System.setProperty("webdriver.chrome.driver", "D:\\Seleium Project\\Istallation Stuff\\Exe Files\\chromedriver_win32\\chromedriver.exe");
 WebDriver driver =new ChromeDriver();
 
 driver.get("https://www.myntra.com/");
 
 driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
 
Alert myAlert = driver.switchTo().alert();
 myAlert.accept();

driver.findElement(By.xpath("//input [@class ='desktop-searchBar']")).sendKeys("Mens Jackets");
 
driver.findElement(By.className("myntraweb-sprite desktop-iconSearch sprites-search")).click();

> 
> **Below is the console log i got .** 
> ---------------------------------

Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 41714
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
May 18, 2019 11:19:45 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.NoAlertPresentException: no such alert
  (Session info: chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SHYAMSUNDHAR-PC', ip: '192.168.0.125', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{mobileEmulationEnabled=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, hasTouchScreen=false, platform=XP, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:50464}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=ignore, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}), userDataDir=C:\Users\SHYAMS~1\AppData\Local\Temp\scoped_dir6836_14826}, takesHeapSnapshot=true, pageLoadStrategy=normal, strictFileInteractability=false, databaseEnabled=false, handlesAlerts=true, version=74.0.3729.157, browserConnectionEnabled=false, proxy=Proxy(), nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7cb6f208163b0ed79297d07c00a106b7
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.alert(RemoteWebDriver.java:1020)
	at module5.MouseEvent.main(MouseEvent.java:20)

**Comment by Sankaramurthy** [comment]
![Myntra Error](https://user-images.githubusercontent.com/49619680/57978787-51732e80-7a31-11e9-9e71-b1b1f417c274.JPG)

**Comment by tabhresh** [comment]
You don't have to handle this notification its not going to obstruct its browser level notification.
